version: '3.3'

services:
  lettuce-pokedex:
    build: .
    container_name: lettuce-pokedex
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
networks:
  default:
    external:
      name: nginx
